name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    uses: sigiuscom/workflows/.github/workflows/actionlint.yml@1ebbe82b1fafeb8066e17d58980a323f9da117cc

  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@b606fc16d412cba3d29c06b8c52ed55d72205a44 # main

  opengrep:
    uses: sigiuscom/workflows/.github/workflows/opengrep.yml@b606fc16d412cba3d29c06b8c52ed55d72205a44 # main
    with:
      config: |
        p/typescript
        p/javascript
        p/react
        p/owasp-top-ten
        p/secrets

  node:
    uses: sigiuscom/workflows/.github/workflows/node-app.yml@b606fc16d412cba3d29c06b8c52ed55d72205a44 # main
    with:
      package-manager: npm
      typecheck-cmd: 'npx tsc --noEmit'