name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@5e687b3de3434965b45bd67919ceb2512ab76909 # main
    secrets: inherit

  opengrep:
    uses: sigiuscom/workflows/.github/workflows/opengrep.yml@5e687b3de3434965b45bd67919ceb2512ab76909 # main
    with:
      config: |
        p/typescript
        p/javascript
        p/react
        p/owasp-top-ten
        p/secrets

  node:
    uses: sigiuscom/workflows/.github/workflows/node-app.yml@5e687b3de3434965b45bd67919ceb2512ab76909 # main
    with:
      package-manager: npm
      typecheck-cmd: 'npx tsc --noEmit'