name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    uses: sigiuscom/workflows/.github/workflows/actionlint.yml@96c8930ba5571658047132774b0d32ceee319a00

  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@39f1613a5407bf7737a1cf353c81ce0dd78f4be1 # main

  opengrep:
    uses: sigiuscom/workflows/.github/workflows/opengrep.yml@39f1613a5407bf7737a1cf353c81ce0dd78f4be1 # main
    with:
      config: |
        p/typescript
        p/javascript
        p/react
        p/owasp-top-ten
        p/secrets

  node:
    uses: sigiuscom/workflows/.github/workflows/node-app.yml@39f1613a5407bf7737a1cf353c81ce0dd78f4be1 # main
    with:
      package-manager: npm
      typecheck-cmd: 'npx tsc --noEmit'